platform :ios, '5.0'
pod 'AFNetworking',     '~> 1.2.0'
pod 'AFIncrementalStore', '0.4.0'
pod 'MBProgressHUD',    '~> 0.6'
pod 'InAppSettingsKit', '~> 1.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 2.0beta4'
pod 'EDColor', '~> 0.2.0'
pod 'DEFacebookComposeViewController', '~> 1.0.0'
pod 'google-plus-ios-sdk', '~> 1.2.1'